import styles from "./overview.module.css";

const researchAreas = [
  {
    number: "01",
    title: "Focused Laser Differential Interferometry",
    description:
      "Development of a focused laser differential interferometer for quantitative measurements of density fluctuations in high-speed flows. The work involved designing and aligning the optical system, developing the measurement and signal-processing methodology, and applying FLDI to investigate unsteady phenomena and screech in supersonic jets.",
    image: "/images/research/fldi.jpg",
    reverse: false,
  },
  {
    number: "02",
    title: "Supersonic Jet Flows",
    description:
      "Experimental investigation of the flow and acoustic behaviour of supersonic free jets, with particular focus on shock-cell structures, instability, and screech. Schlieren imaging, FLDI, and microphone measurements were used to connect unsteady flow structures with the sound generated by the jet, with Schlieren-based Momentum Potential Theory also implemented to examine the acoustic field.",
    image: "/images/research/sonic-jets.jpg",
    reverse: true,
  },
  {
    number: "03",
    title: "Boundary-Layer Transition",
    description:
      "Experimental investigation of boundary-layer transition in high-speed flow through the development and assessment of passive boundary-layer trips. Schlieren imaging, infrared thermography, and temporal pressure measurements were used to examine the evolution of the boundary layer and identify the onset and development of transition.",
    image: "/images/research/boundary-layer.jpg",
    reverse: false,
  },
  {
    number: "04",
    title: "High-Speed Cylinder Wake Flows",
    description:
      "Investigation of the unsteady wake behind a cylinder in high-speed flow, focusing on the interaction between the near-wake shear layers and the resulting flow oscillations. The work explored how these interactions contribute to aeroacoustic feedback and how modifications such as a splitter plate can influence the dominant unsteady behaviour.",
    image: "/images/research/cylinder-wake.jpg",
    reverse: true,
  },
  {
    number: "05",
    title: "Supersonic Exhaust Diffuser",
    description:
      "Design and investigation of a supersonic exhaust diffuser for high-altitude rocket motor testing at SDSC, ISRO. The work examined diffuser flow behaviour and starting characteristics to understand the conditions required for reliable operation during simulated high-altitude testing.",
    image: "/images/research/diffuser.jpg",
    reverse: false,
  },
  {
    number: "06",
    title: "Supersonic Nozzles: Flow & Acoustics",
    description:
      "Experimental and computational investigation of configured supersonic nozzles to understand how nozzle geometry influences jet structure and acoustic behaviour. The work examined modified chevron and beveled nozzle configurations using flow visualization, acoustic measurements, and computational analysis to investigate changes in jet development, instability, and noise.",
    image: "/images/research/nozzles.jpg",
    reverse: true,
  },
];

export default function ResearchOverviewPage() {
  return (
    <main className={styles.overviewPage}>

      {/* HERO */}

      <section className={styles.hero}>
        <div className={styles.heroInner}>
          <h1 className={styles.heroTitle}>
            Research at
            <br />
            a glance.
          </h1>
        </div>
      </section>


      {/* RESEARCH PROJECTS */}

      <section className={styles.researchSection}>

        {researchAreas.map((research) => (
          <article
            className={`${styles.researchItem} ${
              research.reverse ? styles.reverse : ""
            }`}
            key={research.number}
          >

            {/* IMAGE */}

            <div className={styles.imageWrapper}>
              <img
                src={research.image}
                alt={research.title}
                className={styles.researchImage}
              />
            </div>


            {/* PROJECT INFORMATION */}

            <div className={styles.researchContent}>

              <span className={styles.researchNumber}>
                {research.number}
              </span>

              <h2 className={styles.researchTitle}>
                {research.title}
              </h2>

              <p className={styles.researchDescription}>
                {research.description}
              </p>

            </div>

          </article>
        ))}

      </section>

    </main>
  );
}